#  This file serves as a template for the environment variables
#  that will need to be set for this application.

#  To use the template, fill in your own information for each
#  variable and save as config/application.yml

#  Note: config/application.yml is git ignored to prevent
#  sharing of personal information.  This template is NOT ignored.
#  Please do not store any personal or confidential information
#  in this template.


# PRODUCTION VALUES
production:
  #  Credentials for S3 storage on Amazon
  S3_BUCKET_NAME: "your bucket name"
  AWS_ACCESS_KEY_ID: "your aws access key id"
  AWS_SECRET_ACCESS_KEY: "your aws secret access key"
# Email
  EMAIL_FROM: 'your_name@your-domain.com'
  EMAIL_TO: 'address where emails from contact form should be sent'
  EMAIL_REPLY_TO: 'your_name@your-domain.com'
  EMAIL_HOST: 'http://your-domain.com'
  SENDGRID_USERNAME: 'your sendgrid username'
  SENDGRID_PASSWORD: 'your sendgrid password'


# DEVELOPMENT VALUES
development:
  #  Credentials for S3 storage on Amazon
  S3_BUCKET_NAME: "your bucket name"
  AWS_ACCESS_KEY_ID: "your aws access key id"
  AWS_SECRET_ACCESS_KEY: "your aws secret access key"
# Email
  EMAIL_FROM: 'your_name@your-domain.com'
  EMAIL_TO: 'address where emails from contact form should be sent'
  EMAIL_REPLY_TO: 'your_name@your-domain.com'
  EMAIL_HOST: 'http://your-domain.com'
  SENDGRID_USERNAME: 'your sendgrid username'
  SENDGRID_PASSWORD: 'your sendgrid password'



# TEST VALUES
test:
  #  Credentials for S3 storage on Amazon
  S3_BUCKET_NAME: "your bucket name"
  AWS_ACCESS_KEY_ID: "your aws access key id"
  AWS_SECRET_ACCESS_KEY: "your aws secret access key"
  # Email
  EMAIL_FROM: 'your_name@your-domain.com'
  EMAIL_TO: 'address where emails from contact form should be sent'
  EMAIL_REPLY_TO: 'your_name@your-domain.com'
  EMAIL_HOST: 'http://your-domain.com'
